### ISSUE TITLE
Missed python ?

### ISSUE THREAD

**Issue by ArqTras** [ivoryguru/aeonwallet#1]
root@dell:/home/arek/test/aeonwallet/external-libs# sudo make install
script/toolchain-build.sh
installing /opt/android/ndk-r15c arm --api 21 --stl=libc++
script/toolchain-build.sh: linia 17: make_standalone_toolchain.py: command not found
make: *** [Makefile:13: toolchain] Error 127

Nah missed symlink to ndk on ubuntu

**Comment by ivoryguru** [comment]
Cheers, yeah I should mention you need ndk... Glad you got it going.
